name: IHope Local
values:
  - key: baseUrl
    value: 'http://localhost:8080'
  - key: device_id
    value: postman-device-1
  - key: access_token
    value: ''
  - key: refresh_token
    value: ''
  - key: old_access_token
    value: ''
  - key: old_refresh_token
    value: ''
  - key: reset_token
    value: ''
  - key: login_password
    value: password123
