name: IHope Alice
values:
  - key: baseUrl
    value: 'http://localhost:8080'
  - key: ws_base_url
    value: 'ws://localhost:8080'
  - key: device_id
    value: postman-alice
  - key: login_email
    value: alice@example.com
  - key: login_username
    value: alice
  - key: login_password
    value: password123
  - key: identity_public_key
    value: ZxfR5oB15T7ae44NVxOswGTMDzqOac+NxAqo8ZGRGyU=
  - key: access_token
    value: ''
  - key: refresh_token
    value: ''
  - key: old_access_token
    value: ''
  - key: old_refresh_token
    value: ''
  - key: reset_token
    value: ''
  - key: peer_user_id
    value: ''
  - key: conversation_id
    value: ''
  - key: member_user_id
    value: ''
  - key: my_user_id
    value: ''
  - key: group_epoch
    value: ''
  - key: message_before_epoch
    value: ''
  - key: message_after_epoch
    value: ''
