name: IHope Bob
values:
  - key: baseUrl
    value: 'http://localhost:8080'
  - key: ws_base_url
    value: 'ws://localhost:8080'
  - key: device_id
    value: postman-bob
  - key: login_email
    value: bob@example.com
  - key: login_username
    value: bob
  - key: login_password
    value: password123
  - key: identity_public_key
    value: BSAhIiMkJSYnKCkqKywtLi8wMTIzNDU2Nzg5Ojs8PT4/
  - key: access_token
    value: ''
  - key: refresh_token
    value: ''
  - key: peer_user_id
    value: ''
  - key: conversation_id
    value: ''
  - key: member_user_id
    value: ''
  - key: my_user_id
    value: ''
  - key: group_epoch
    value: ''
  - key: message_before_epoch
    value: ''
  - key: message_after_epoch
    value: ''
  - key: signal_identity_key
    value: BQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
  - key: signal_signed_pre_key
    value: BQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
  - key: signal_signed_pre_key_sig
    value: AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==
  - key: signal_one_time_pre_key
    value: BQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
  - key: old_access_token
    value: ''
  - key: old_refresh_token
    value: ''
  - key: reset_token
    value: ''
