import type { ManilaMatch, ManilaPlayer, ManilaWare } from '@/api'

const PLAYERS: ManilaPlayer[] = [
  {
    userId: 'u0',
    username: '红方',
    seat: 0,
    cash: 30,
    publicShares: { nutmeg: 1 },
    secretCount: 1,
    encumbered: {},
    accomplicesLeft: 3,
    passedPlacement: false,
    ready: true,
    isHost: true,
    connected: true,
  },
  {
    userId: 'u1',
    username: '蓝方',
    seat: 1,
    cash: 28,
    publicShares: { silk: 1 },
    secretCount: 1,
    encumbered: {},
    accomplicesLeft: 2,
    passedPlacement: false,
    ready: true,
    isHost: false,
    connected: true,
  },
  {
    userId: 'u2',
    username: '绿方',
    seat: 2,
    cash: 26,
    publicShares: { ginseng: 1 },
    secretCount: 0,
    encumbered: {},
    accomplicesLeft: 3,
    passedPlacement: false,
    ready: true,
    isHost: false,
    connected: true,
  },
  {
    userId: 'u3',
    username: '黄方',
    seat: 3,
    cash: 24,
    publicShares: { jade: 1 },
    secretCount: 1,
    encumbered: {},
    accomplicesLeft: 2,
    passedPlacement: false,
    ready: true,
    isHost: false,
    connected: true,
  },
]

const SEAT_COSTS: Record<ManilaWare, number[]> = {
  nutmeg: [3, 4, 5],
  silk: [3, 4, 5],
  ginseng: [2, 3, 4],
  jade: [2, 3, 4, 5],
}

function puntSlots(index: number, ware: ManilaWare) {
  return SEAT_COSTS[ware].map((cost, seatIndex) => ({
    id: `punt${index}_${seatIndex}`,
    kind: 'punt',
    cost,
    payout: 0,
    label: ware,
    puntIndex: index,
    seatIndex,
    ware,
  }))
}

/** Mid-voyage demo: sea + port berth + yard berth + shore + pirate + market. */
export function buildManilaDemoMatchWithYard(): ManilaMatch {
  return {
    phase: 'place',
    voyage: 2,
    players: PLAYERS,
    harborMasterId: 'u0',
    auctionHighBid: 0,
    auctionPassed: [],
    turnUserId: 'u1',
    market: { nutmeg: 10, silk: 5, ginseng: 20, jade: 0 },
    shareSupply: { nutmeg: 3, silk: 3, ginseng: 3, jade: 3 },
    punts: [
      { index: 0, ware: 'nutmeg', position: 3, arrived: false, die: 2 },
      { index: 1, ware: 'silk', position: 13, arrived: true, berth: 'shipyard_B' },
      { index: 2, ware: 'jade', position: 13, arrived: true, berth: 'port_B' },
    ],
    occupied: [
      { slotId: 'punt0_0', userId: 'u0', cost: 3 },
      { slotId: 'punt0_2', userId: 'u1', cost: 5 },
      { slotId: 'punt2_1', userId: 'u2', cost: 3 },
      { slotId: 'punt2_3', userId: 'u3', cost: 5 },
      { slotId: 'port_A', userId: 'u0', cost: 4 },
      { slotId: 'port_C', userId: 'u1', cost: 2 },
      { slotId: 'shipyard_A', userId: 'u2', cost: 4 },
      { slotId: 'shipyard_C', userId: 'u3', cost: 2 },
      { slotId: 'pirate_0', userId: 'u1', cost: 5 },
      { slotId: 'pilot_large', userId: 'u0', cost: 5 },
      { slotId: 'insurance', userId: 'u3', cost: 0 },
    ],
    placeRound: 2,
    moveRound: 2,
    maxPlaceRounds: 3,
    events: ['效果预览 · 演示布局'],
    version: 1,
    slots: [
      ...puntSlots(0, 'nutmeg'),
      ...puntSlots(1, 'silk'),
      ...puntSlots(2, 'jade'),
      { id: 'port_A', kind: 'port', cost: 4, payout: 6, label: 'port_A', berth: 'A' },
      { id: 'port_B', kind: 'port', cost: 3, payout: 8, label: 'port_B', berth: 'B' },
      { id: 'port_C', kind: 'port', cost: 2, payout: 15, label: 'port_C', berth: 'C' },
      { id: 'shipyard_A', kind: 'shipyard', cost: 4, payout: 6, label: 'shipyard_A', berth: 'A' },
      { id: 'shipyard_B', kind: 'shipyard', cost: 3, payout: 8, label: 'shipyard_B', berth: 'B' },
      { id: 'shipyard_C', kind: 'shipyard', cost: 2, payout: 15, label: 'shipyard_C', berth: 'C' },
      { id: 'pirate_0', kind: 'pirate', cost: 5, payout: 0, label: '海盗船长', pirateRank: 0 },
      { id: 'pirate_1', kind: 'pirate', cost: 5, payout: 0, label: '海盗水手', pirateRank: 1 },
      { id: 'pirate_2', kind: 'pirate', cost: 5, payout: 0, label: '海盗水手', pirateRank: 2 },
      { id: 'pilot_small', kind: 'pilot', cost: 2, payout: 0, label: '小领航', pilotSize: 'small' },
      { id: 'pilot_large', kind: 'pilot', cost: 5, payout: 0, label: '大领航', pilotSize: 'large' },
      { id: 'insurance', kind: 'insurance', cost: 0, payout: 0, label: '保险' },
    ],
  }
}
